export const SUPER_ADMIN_EMAIL = "itentad.work@gmail.com";

export const defaultSiteCopy = {
  home_account_label: "Tài khoản",
  home_my_jars: "lọ của tôi",
  home_login: "đăng nhập",
  home_signup: "đăng ký",
  home_kicker: "một món quà từ rất nhiều người thương",
  home_title_first: "a little jar",
  home_title_second: "of stars",
  home_intro_first: "Mỗi người gấp một lá thư thành ngôi sao.",
  home_intro_second: "Đến ngày đặc biệt, cả chiếc lọ sẽ mở ra cho một người.",
  home_create: "★ tạo lọ quà tặng",
  home_recipient_help_link: "tôi nhận được một liên kết",
  home_help_close: "Đóng",
  home_help_title: "Bạn là người nhận?",
  home_help_body: "Hãy mở đúng liên kết người tặng đã gửi riêng cho bạn, rồi nhập mật mã họ cung cấp. Chỉ có mật mã thôi thì chưa đủ — hãy xin thêm liên kết chiếc lọ.",
  home_help_confirm: "mình hiểu rồi",

  auth_back: "quay về",
  auth_email_label: "Email",
  auth_email_placeholder: "ban@example.com",
  auth_password_label: "Mật khẩu",
  auth_google: "tiếp tục với Google",
  login_title: "đăng nhập quản lý",
  login_intro: "mở cánh cửa riêng dẫn tới những chiếc lọ của bạn.",
  login_password_placeholder: "mật khẩu",
  login_submit: "đăng nhập",
  login_error: "Email hoặc mật khẩu chưa đúng.",
  login_signup_link: "chưa có tài khoản? đăng ký",
  signup_title: "đăng ký",
  signup_intro: "tạo tài khoản để giữ những chiếc lọ của bạn an toàn.",
  signup_password_placeholder: "ít nhất 8 ký tự",
  signup_submit: "tạo tài khoản",
  signup_sent: "Hãy mở email để xác nhận tài khoản.",
  signup_login_link: "đã có tài khoản? đăng nhập",

  admin_back_home: "trang chủ",
  admin_title: "những chiếc lọ của tôi",
  admin_intro: "mỗi chiếc lọ là một món quà dành riêng cho một người.",
  admin_create: "+ tạo chiếc lọ mới",
  admin_settings: "chỉnh chữ trên website",
  admin_jars_label: "Danh sách những chiếc lọ",
  admin_for: "dành cho",
  admin_empty: "Chưa có chiếc lọ nào — bắt đầu tạo chiếc đầu tiên nhé.",
  admin_detail_back: "các chiếc lọ",
  admin_for_recipient: "dành cho",
  admin_share_title: "gửi đúng link cho đúng người",
  admin_share_intro: "Hai link này có quyền khác nhau, đừng gửi nhầm link người nhận vào nhóm.",
  admin_contributor_link_title: "1. Link cho nhóm bạn viết thư",
  admin_contributor_link_body: "Gửi vào nhóm. Mỗi người chỉ sửa được thư của chính mình.",
  admin_contributor_link_label: "link cho người viết",
  admin_recipient_link_title: "2. Link riêng cho người nhận",
  admin_recipient_link_body: "Chỉ gửi khi bạn đã duyệt thư và bấm mở lọ.",
  admin_recipient_link_label: "link cho người nhận",
  admin_hint_prefix: "Gợi ý mật mã:",
  admin_no_hint: "không có",
  admin_hint_delivery: "Hãy gửi mật mã riêng qua Messenger hoặc Zalo.",
  admin_controls_title: "điều khiển chiếc lọ",
  admin_collect: "nhận thêm thư",
  admin_lock: "niêm phong lọ",
  admin_open: "mở lọ cho người nhận",
  admin_gallery_on: "bật thư chia sẻ giữa người viết",
  admin_gallery_off: "tắt thư chia sẻ giữa người viết",
  admin_letters_title: "thư đã nhận",
  admin_letters_intro: "Duyệt thư để biến nó thành một ngôi sao trong lọ người nhận.",
  admin_approve: "duyệt",
  admin_hide: "ẩn",
  admin_no_letters: "Chưa có thư. Hãy sao chép link cho người viết và gửi vào nhóm bạn.",
  status_collecting: "đang nhận thư",
  status_locked: "đã niêm phong",
  status_opened: "đã mở",
  status_pending: "đang chờ duyệt",
  status_approved: "đã duyệt",
  status_hidden: "đã ẩn",
  visibility_private: "riêng tư",
  visibility_contributors: "chia sẻ với người viết",

  create_back: "những chiếc lọ của tôi",
  create_title: "tạo một chiếc lọ",
  create_intro: "một người nhận, nhiều người thương và một mật mã chỉ họ biết.",
  create_recipient_label: "Tên người nhận",
  create_recipient_placeholder: "Linh",
  create_title_label: "Tên của chiếc lọ",
  create_title_placeholder: "Một chiếc lọ nhỏ dành cho Linh",
  create_note_label: "Lời nhắn trước khi chiếc lọ mở",
  create_note_placeholder: "Mọi người đã bí mật lấp đầy chiếc lọ này bằng những lá thư…",
  create_passcode_label: "Mật mã dành cho người nhận",
  create_passcode_placeholder: "Ít nhất 6 ký tự",
  create_hint_label: "Gợi ý mật mã",
  create_hint_placeholder: "Ngày đầu tiên chúng ta gặp nhau — DDMMYYYY",
  create_open_at_label: "Ngày giờ mở (không bắt buộc)",
  create_open_manual: "Mở thủ công (tự bạn bấm mở)",
  create_open_scheduled: "Hẹn ngày giờ mở",
  create_open_date: "Ngày",
  create_open_time: "Giờ",
  create_submit: "tạo chiếc lọ này",
  create_pending: "đang gấp chiếc lọ…",

  contribute_back: "về trang chủ",
  contribute_writing_for: "bạn đang viết cho",
  contribute_closed_title: "Chiếc lọ đã ngừng nhận thư",
  contribute_closed_body: "Chủ lọ đã niêm phong món quà này rồi.",
  letter_success_eyebrow: "đã gửi thành công",
  letter_success_title: "Một ngôi sao vừa rơi vào lọ rồi đó ★",
  letter_edit_link: "giữ lại đường dẫn sửa thư",
  letter_gallery_link: "ghé xem những lá thư được chia sẻ",
  letter_eyebrow: "một lá thư, một ngôi sao",
  letter_title: "Hãy viết cái gì cảm động vào đây =))))",
  letter_intro: "Đừng chỉ viết “chúc mừng nha”. Kể một chuyện cũ, thú nhận một điều chưa nói, hoặc làm người ta cười trước khi khóc.",
  letter_sender_label: "Ký tên để người ta còn biết ai làm mình cảm động",
  letter_sender_placeholder: "Tên hoặc biệt danh của bạn",
  letter_sender_anonymous_placeholder: "Danh tính đã được giấu kỹ",
  letter_anonymous: "Ngại quá thì giấu tên, người nhận sẽ thấy “ẩn danh”.",
  letter_content_label: "Lá thư của bạn",
  letter_content_placeholder: "Một kỷ niệm, một lời chưa nói, một lời cảm ơn thật dài… cứ viết đi, tờ giấy này giữ bí mật giỏi lắm.",
  letter_font_label: "Chọn nét chữ hợp với độ sến của bạn",
  letter_font_handwritten: "Viết tay",
  letter_font_handwritten_hint: "Thân mật như viết trong sổ",
  letter_font_serif: "Thư tình",
  letter_font_serif_hint: "Mềm mại và hơi điện ảnh",
  letter_font_typewriter: "Máy chữ",
  letter_font_typewriter_hint: "Tinh nghịch kiểu thư bí mật",
  letter_color_label: "Màu ngôi sao",
  letter_edit_passcode_label: "Mật mã cứu nguy nếu lát nữa thấy sến quá",
  letter_edit_passcode_placeholder: "Ít nhất 6 ký tự",
  letter_share: "Cho hội bạn đọc ké sau khi chủ lọ duyệt.",
  letter_private_note: "Chỉ bạn mới sửa được lá thư bằng đường dẫn và mật mã riêng. Nhớ cất cả hai ở nơi an toàn nhé.",
  letter_submit: "gấp lại rồi thả vào lọ ★",
  letter_pending: "đang gấp thành ngôi sao…",
  counter_words: "từ",
  counter_characters: "ký tự",
  color_sky: "Xanh trời",
  color_lavender: "Tím mơ",
  color_mint: "Xanh bạc hà",
  color_sage: "Xanh lá dịu",
  color_pink: "Hồng phấn",
  color_peach: "Cam đào",
  color_coral: "Đỏ san hô",
  color_yellow: "Vàng nắng",

  edit_back: "quay lại chiếc lọ",
  edit_page_eyebrow: "một góc chỉ mình bạn biết",
  edit_page_title: "Lá thư đã gấp",
  edit_page_intro: "Chỉ đường dẫn này cùng mật mã riêng mới mở được phần chỉnh sửa.",
  edit_private: "khu vực riêng tư",
  edit_unlock_title: "Mở lại lá thư của bạn",
  edit_passcode_label: "Mật mã sửa thư",
  edit_unlock: "mở lá thư",
  edit_checking: "đang kiểm tra…",
  edit_eyebrow: "được phép đổi ý",
  edit_title: "Sửa lại trước khi ngôi sao được mở",
  edit_intro: "Sửa xong, thư sẽ quay lại chờ chủ lọ duyệt một lần nữa.",
  edit_sender_label: "Tên hoặc biệt danh",
  edit_anonymous: "Gửi ẩn danh.",
  edit_font_label: "Kiểu chữ",
  edit_save: "lưu và gấp lại ★",
  edit_saving: "đang gấp lại…",

  recipient_back: "trang chủ",
  recipient_for: "một chiếc lọ dành cho",
  recipient_secret_title: "một bí mật nhỏ đang giữ chiếc lọ an toàn",
  recipient_sealed_title: "chiếc lọ vẫn đang được niêm phong",
  recipient_passcode_label: "Mật mã riêng",
  recipient_hint_prefix: "gợi ý:",
  recipient_unlock: "mở chiếc lọ của tôi",
  recipient_checking: "đang kiểm tra…",
  recipient_waiting: "Chủ lọ chưa mở món quà này. Hãy quay lại khi họ gửi tín hiệu cho bạn nhé.",
  recipient_made_for: "được làm bằng rất nhiều yêu thương cho",
  recipient_tap_star: "chạm vào từng ngôi sao để mở một lá thư.",
  recipient_empty: "chiếc lọ đã mở nhưng chưa có thư nào được duyệt.",
  recipient_jar_alt: "Một chiếc lọ thủy tinh chứa những ngôi sao giấy",
  recipient_open_star: "Mở ngôi sao",
  recipient_close: "Đóng",
  recipient_anonymous: "ẩn danh",
  recipient_fold_back: "gấp lại vào lọ",
  recipient_dialog_label: "Lá thư đã mở",
  recipient_view_all: "xem tất cả ngôi sao",
  recipient_gallery_title: "tất cả ngôi sao trong lọ",
  recipient_gallery_intro: "những ngôi sao đã mở sẽ hiện nội dung ở đây.",
  recipient_gallery_unopened: "ngôi sao chưa mở",

  gallery_back: "quay lại viết thư",
  gallery_title: "những lá thư được chia sẻ",
  gallery_intro: "Chỉ những thư đã được chủ lọ duyệt và người viết đồng ý chia sẻ mới xuất hiện ở đây.",
  gallery_private_title: "chỉ dành cho người đã viết thư",
  gallery_private_body: "Hãy gửi một lá thư từ trình duyệt này trước khi ghé vào góc nhỏ này.",
  gallery_anonymous: "ẩn danh",
  gallery_empty: "Chưa có lá thư chia sẻ nào được duyệt.",

  copy_done: "đã sao chép ✓",
  copy_error: "không sao chép được",
  copy_action: "sao chép",

  settings_back: "quay lại quản trị",
  settings_title: "chỉnh chữ trên website",
  settings_intro: "Chỉ thay đổi chữ giao diện cố định. Tên người nhận, tên lọ và nội dung thư không nằm ở đây.",
  settings_saved: "Đã lưu và cập nhật toàn bộ website.",
  settings_submit: "lưu toàn bộ thay đổi",

  error_invalid_slug: "Đường dẫn chiếc lọ không hợp lệ.",
  error_letter_length: "Lá thư cần dài từ 1 đến 10.000 ký tự.",
  error_sender_required: "Bạn chưa ký tên cho lá thư.",
  error_edit_passcode_length: "Mật mã sửa thư cần từ 6 đến 72 ký tự.",
  error_font_invalid: "Kiểu chữ bạn chọn không hợp lệ.",
  error_letter_submit: "Chưa thể thả lá thư vào lọ. Hãy thử lại nhé.",
  success_letter_submit: "Lá thư đã được gấp an toàn. Hãy giữ lại đường dẫn sửa thư và mật mã riêng của bạn.",
  error_letter_load: "Mật mã chưa đúng hoặc lá thư không còn tồn tại.",
  error_letter_update: "Chưa thể sửa lá thư. Kiểm tra mật mã hoặc nhắn chủ chiếc lọ nhé.",
  success_letter_update: "Đã gấp lại lá thư. Thư đang chờ chủ lọ duyệt lần nữa.",
  error_recipient_unlock: "Không thể mở khóa chiếc lọ lúc này.",
  error_recipient_not_opened: "Chiếc lọ vẫn đang được niêm phong. Chủ lọ sẽ báo khi món quà sẵn sàng.",
  error_recipient_locked: "Bạn đã thử quá nhiều lần. Hãy quay lại sau 15 phút.",
  error_recipient_wrong_passcode: "Mật mã này chưa mở được chiếc lọ.",
  error_star_open: "Không thể mở ngôi sao này.",
} as const;

export type SiteCopyKey = keyof typeof defaultSiteCopy;
export type SiteCopy = { [Key in SiteCopyKey]: string };

export const siteCopyGroups = [
  ["Trang chủ", "home_"], ["Đăng nhập và đăng ký", "auth_", "login_", "signup_"],
  ["Quản trị", "admin_", "status_", "visibility_"], ["Tạo lọ", "create_"], ["Viết thư", "contribute_", "letter_", "counter_", "color_"],
  ["Sửa thư", "edit_"], ["Người nhận", "recipient_"], ["Thư chia sẻ", "gallery_"],
  ["Sao chép liên kết", "copy_"], ["Trang cài đặt", "settings_"], ["Thông báo hệ thống", "error_", "success_"],
] as const;

export const mergeSiteCopy = (value: unknown): SiteCopy => {
  const saved = value && typeof value === "object" ? value as Record<string, unknown> : {};
  return Object.fromEntries(Object.entries(defaultSiteCopy).map(([key, fallback]) => [key, typeof saved[key] === "string" && saved[key].trim() ? saved[key] : fallback])) as SiteCopy;
};
